version: "3.0"

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456@abc
      - POSTGRES_DB=DB4RENT
    ports:
      - "5432:5432"
